title: <p align="center"> Helena Bardsley </p>

logo: "/images/PFP.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/helena-bardsley-4b6616209/">LinkedIn</a> |
  <a href="https://github.com/helenabardsley">GitHub</a>
  </p>
  
  <p align="justify">
  Currently, I am pursing a graduate degree in Applied Analytics (M.S.) at Columbia University.
  <br><br>
  I am actively looking for internships...
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
