title: <p align="center"> Helena Bardsley </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/helena-bardsley-4b6616209/">LinkedIn</a> |
  <a href="https://github.com/helenabardsley">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing MS degree in Applied Analytics at Columbia University.
  <br><br>
  I am currently looking for internships...
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
