title: <p align="center"> Helena Bardsley </p>

logo: "/images/PFP.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/helena-bardsley-4b6616209/">LinkedIn</a> |
  <a href="https://github.com/helenabardsley">GitHub</a>
  </p>
  
  <p align="justify">
  Hi! If you are reading this, I just wanted to let you know that this website is currently under construction :). Regardless, I still hope you can get a sense of my background through my unfinished portfolio!
  <br><br>
  I am actively looking for internships...
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
